### ISSUE TITLE
Feature Request: Enable frontmatter to allow more descriptive filenames

### ISSUE THREAD

**Issue by reidjs** [reidjs/markdown-tweet-scheduler#14]
What about an alternative format that lets you have a more descriptive filename but the markdown file contains frontmatter that has the date in it? GitHub supports markdown files with frontmatter. (frontmatter is header values in YAML format surrounded by ---)

suggested by https://github.com/swharden @swharden 

(shouldn't break the original workflow)

**Comment by caioeverest** [comment]
Hey, @reidjs I open a pull request (PR-#17) addressing this issue, could you take a look?
